In [1]:
import numpy as np

In [ ]:
list = (1,2,3,4,5,6,7,8,9,10)
array = np.array(list)
print(array)
print(array.size)
print(array.ndim)
print(array.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
10
1
int64
<built-in method astype of numpy.ndarray object at 0x0000025DB4D13B70>


In [7]:
list2 = (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
array1 = np.array(list2)
reshape1 = np.reshape(array1 , (4,5))
reshape2 = np.reshape(array1 , (2,10))
reshape3 = np.reshape(array1 , (5,4))
print(reshape1)
print(reshape2)
print(reshape3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [10]:
array2 = np.array([[1,2,3,4] ,[5,6,7,8] ,[9,10,11,12]])
first_row = array2[0,:]
last_row = array2[2,:]
middle = array2[1,(1,2)]
all_even = array2[array2 % 2 == 0]
print(first_row)
print(last_row)
print(middle)
print(all_even)

[1 2 3 4]
[ 9 10 11 12]
[6 7]
[ 2  4  6  8 10 12]


In [14]:
array3 = np.arange(1,26)
array3[array3 % 3 == 0] = -1
array3[array3 > 20 ] = 999
print(array3)

[  1   2  -1   4   5  -1   7   8  -1  10  11  -1  13  14  -1  16  17  -1
  19  20  -1 999 999  -1 999]


In [19]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(pow(a,2))
print(pow(b,2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]
[ 1  4  9 16]
