In [10]:
import numpy as np

In [11]:
list = (1,2,3,4,5,6,7,8,9,10)
array = np.array(list)
print(array)
print(array.size)
print(array.ndim)
print(array.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
10
1
int64


In [12]:
list2 = (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
array1 = np.array(list2)
reshape1 = np.reshape(array1 , (4,5))
reshape2 = np.reshape(array1 , (2,10))
reshape3 = np.reshape(array1 , (5,4))
print(reshape1)
print(reshape2)
print(reshape3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [13]:
array2 = np.array([[1,2,3,4] ,[5,6,7,8] ,[9,10,11,12]])
first_row = array2[0,:]
last_row = array2[2,:]
middle = array2[1,(1,2)]
all_even = array2[array2 % 2 == 0]
print(first_row)
print(last_row)
print(middle)
print(all_even)

[1 2 3 4]
[ 9 10 11 12]
[6 7]
[ 2  4  6  8 10 12]


In [14]:
array3 = np.arange(1,26)
array3[array3 % 3 == 0] = -1
array3[array3 > 20 ] = 999
print(array3)

[  1   2  -1   4   5  -1   7   8  -1  10  11  -1  13  14  -1  16  17  -1
  19  20  -1 999 999  -1 999]


In [15]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(pow(a,2))
print(pow(b,2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]
[ 1  4  9 16]


In [16]:
array4 = np.arange(1,17)
array4 = array4.reshape(4,4)
print(array4)
row_sum = np.sum(array4 , axis=1)
print(row_sum)
col_sum = np.sum(array4 , axis=0)
print(col_sum)
total_sum = np.sum(array4)
print(total_sum)
row_mean = np.mean(array4 , axis=1)
print(row_mean)
max_col = np.max(array4 , axis=0)
print(max_col)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]
136
[ 2.5  6.5 10.5 14.5]
[13 14 15 16]


In [17]:
array5 = np.eye(3,3)
print(array5)
array6 = np.zeros((3,3))
print(array6)
array7 = np.full((3,3) , 7)
print(array7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [20]:
list3 = [[1, 2, 3], [4, 5, 6]]
array8 = np.array(list3)
flatened_array = array8.flatten()
print(flatened_array)
flatened_array_1 = array8.reshape(6)
print(flatened_array_1)
flatened_array_2 = array8.ravel()
print(flatened_array_2)
flatened_array_2[1] = 999
print(array8)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[  1 999   3]
 [  4   5   6]]


In [27]:
array9 = np.linspace(1,100 ,15 ,dtype=int)
print(array9)
print(max(array9))
print(min(array9))
print(np.argmax(array9))
print(np.argmin(array9))
print(np.sort(array9))

[  1   8  15  22  29  36  43  50  57  64  71  78  85  92 100]
100
1
14
0
[  1   8  15  22  29  36  43  50  57  64  71  78  85  92 100]
