In [2]:
import numpy as np

In [ ]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
transpose_array1 = np.transpose(array1)
print(transpose_array1)
reversed_1 = array1[:,::-1 ]
print(reversed_1)
reversed_2 = array1[::-1 ,:]
print(reversed_2)
#Important 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [20]:
array2 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(array2)
print(array2.shape)
print(array2.ndim)
print(array2.size)
sliced_array2 = array2[0,:,:]
print(sliced_array2)
print(array2[0,0,0])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)
3
24
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1


In [23]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a+b)
print(a*b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [29]:
v = np.array([3, 4])
v_mean = v.mean()
print(v_mean)
v_std = np.std(v)
print(v_std)
normalized_v = (v - v_mean)/v_std
print(normalized_v)
print(normalized_v.mean())
print(np.std(normalized_v))

3.5
0.5
[-1.  1.]
0.0
1.0


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])
# arr1 = arr[0:2]
# arr2 = arr[2:4]
# arr3 = arr[4:6]
# print(arr1,arr2,arr3)

splited = np.split(arr , 3)
print(splited)
merged_1 = np.concatenate(splited)
print(merged_1)
merged_2 = np.vstack(splited)
print(merged_2)


[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [49]:
array3 = np.eye(4,4)
print(array3)
print(array3.diagonal())
np.fill_diagonal(array3 , 0)
print(array3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [62]:
arr1 = np.array([
    [2, 5, 8],
    [1, 7, 4],
    [9, 3, 6]
])

mean_arr1 = arr1.mean()
std_dev = np.std(arr1)
median_arr1 = np.median(arr1)
variance_arr1 = np.var(arr1)
print(mean_arr1)
print(arr1[arr1 > mean_arr1])
arr4 = arr1[arr1 > mean_arr1]
print(median_arr1)
print(arr1[arr1 < median_arr1 ])
arr5 = arr1[arr1 < median_arr1 ]

5.0
[8 7 9 6]
5.0
[2 1 4 3]


In [70]:
array_5 = np.array([
    [12,  5, 18,  7, 21],
    [ 9, 15,  3, 27, 11],
    [24,  6, 19, 14,  8],
    [ 2, 30, 16, 10, 25],
    [13,  4, 22, 17, 20]
])
print(arr)
# find the row with the maximum sum 
sum_arr1 = np.sum(array_5 , axis=1)
print(np.argmax(sum_arr1))
sum_arr2 = np.sum(array_5 , axis=0)
print(np.argmin(sum_arr2))
print(np.unravel_index(np.argmax(array_5) , array_5.shape))

[[12  5 18  7 21]
 [ 9 15  3 27 11]
 [24  6 19 14  8]
 [ 2 30 16 10 25]
 [13  4 22 17 20]]
3
0
(np.int64(3), np.int64(1))
