In [1]:
import numpy as np
import time 
import sys

In [2]:
arr = np.array([1 , 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
size = 10_000_000
py_list = list(range(size))
start_time_1 = time.time()
sqaured = [x**2 for x in py_list]
end_time_1 = time.time()
print(f"the total time required in this python list is :---> {end_time_1-start_time_1}")

the total time required in this python list is :---> 0.6512448787689209


In [4]:
np_arr = np.array(py_list)
start_time_2 = time.time()
squared = np_arr ** 2
end_time_2 = time.time()
print(f"the total time required in this numpy array is :---> {end_time_2-start_time_2}")

the total time required in this numpy array is :---> 0.03303933143615723


In [5]:
print(f"the size of the python list is {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"the size of the numpy array is {np_arr.nbytes} bytes")

the size of the python list is 800000560000000 bytes
the size of the numpy array is 80000000 bytes


In [6]:
arr1 = np.array([[1,2,3] , [4,5,6] ,[7,8,9]])
print(arr1)
print(f"the shape of the numpy array is :-> {arr1.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the shape of the numpy array is :-> (3, 3)


In [7]:
arr2 = np.zeros((3,4))
print(arr2 , arr.dtype)

arr3 = np.ones((3,4))
arr4 = np.eye(4)
arr5 = np.arange(10,1,2)
print(arr3)
print(arr4)
print(arr5)

arr6 = np.empty((3,3))
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] int64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
print(arr2.nbytes)
print(arr2.size)

arr_float = arr2.astype(np.float64)
print(arr_float , arr_float.dtype)


(3, 4)
float64
2
96
12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] float64


In [9]:
print(arr2)
reshaped = arr2.reshape((4,3))
print(f"the reshaped array is \n {reshaped}")

flatened = arr2.flatten()
print(f"the flattened array is :-> \n {flatened}")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
the reshaped array is 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
the flattened array is :-> 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
print(arr)
idx = [1 , 2 , 3]
print(arr[idx])

print(arr[arr % 2 != 0])

[1 2 3 4 5]
[2 3 4]
[1 3 5]


In [11]:
print(arr1)
print(f"the sliced array is :- >  ")
sub_arr = arr1[1:,1: ].copy()
sub_arr[0,0] = 200
print(sub_arr)
print(arr1)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
the sliced array is :- >  
[[200   6]
 [  8   9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr_complex = np.array([3 +5j , 2+ 9j])
print(arr_complex.dtype)

complex128


In [13]:
print(arr)

nums = [1,2,3,4,5]
print(nums)
sliced_nums = nums[1:3]
print(sliced_nums)
sliced_nums[0] = 1000
print(sliced_nums)
print(nums)


[1 2 3 4 5]
[1, 2, 3, 4, 5]
[2, 3]
[1000, 3]
[1, 2, 3, 4, 5]


In [14]:
nums = np.array([1,2,3,4,5])
sliced_nums_2 = nums[1:3]
print(sliced_nums_2)
sliced_nums_2[0] = 1000
print(sliced_nums_2)
print(nums)

[2 3]
[1000    3]
[   1 1000    3    4    5]


In [18]:
print(arr1)
print(np.sum(arr1 , axis=0))
print(np.sum(arr1 , axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [24]:
# lets make a 3d array 
array_3d = np.array([[[1,2] , [3,4] , [9,10]] , [[5,6] , [7,8] , [11,12]]])
print(array_3d)
print("the shape of the array is :-> " , array_3d.shape)
print(array_3d[0,1,1])

[[[ 1  2]
  [ 3  4]
  [ 9 10]]

 [[ 5  6]
  [ 7  8]
  [11 12]]]
the shape of the array is :->  (2, 3, 2)
4


In [38]:
array_2d_1 = np.array([1,2,3,4,5])
array_2d_2 = np.array([[11,12,13,14,15]])

print(array_2d_2 + array_2d_1)

[[12 14 16 18 20]]


In [44]:
print(arr1)
mean = np.mean(arr1)
std_dev = np.std(arr1)

normalized_array = (arr1 - mean)/std_dev
print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
